# Generated by Django 5.1.6 on 2025-02-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_recipeingredient_ingredient_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient_field',
            new_name='ingredient',
        ),
    ]
