# Generated by Django 5.1.6 on 2025-02-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_remove_recipeingredient_recipe_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe',
            new_name='recipe_field',
        ),
    ]
