# Generated by Django 5.1.6 on 2025-02-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_rename_recipe_recipeingredient_recipe_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe_field',
            new_name='recipe',
        ),
    ]
