# Generated by Django 5.1.6 on 2025-03-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_recipe_created_on_recipe_updated_on_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='short_bio',
        ),
    ]
